server:
  port : 8080

spring:
  application:
    name: yh-back
  mail:
    host: smtp.gmail.com
    port: 587
    username: projectY
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000
          auth-code-expiration-millis: 1800000
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      #hibernate.hbm2ddl.auto: update
      hibernate:
        format_sql: true
        ddl-auto: true # ? ??? h2?? ???? mariaDB?? ???? ?? hibernate.hbm2ddl.auto: update ? ????
  data:
    rest:
      base-path: /api
      detection-strategy: annotated #????? ? ??? ???
      default-page-size: 10
      max-page-size: 10

  security:
    oauth2:
      client:
        registration:
#          google:
#            client-id: your-google-client-id
#            client-secret: your-google-client-secret
#            scope:
#              - profile
#              - email
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"
#            client-name: Google
#          naver:
#            client-id: m2ddDQMGXBzWxcUdiQvB
#            client-secret: vvSVcrnYJq
#            scope:
#              - profile
#              - email
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/callback/{registrationId}"
#            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
#            client-name: Naver
          kakao:
            #client-id: 1d83d91ec18535215429643ce6417aff
            #client-secret: tCdQvNbqMOtCFq6MZBIgN6BsmY3a0BW3
            client-id: ae8be6119d735b924ca91cba26ff8f48
            client-secret: 26pI1td0SipQiKaQtB7uUog9KR97qJBX
            #redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            #redirect-uri: "http://192.168.0.18:3000/login"
            redirect-uri: "http://localhost:3000/login"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post #카카오는 이 클라이언트 시크릿 포스트가 필요
            scope:
              - account_email
              - name
              - gender
              - age_range
              - birthday
              - birthyear
              - phone_number
            client-name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalababbbaaaaaaaaaabbbbb

logging:
  level:
    org.springframework: debug
